"""The AcoustID decision core against REAL fingerprint answers.

Every row is a file that actually sits in a working SoulSync library, its
expected title/artist, and the recordings AcoustID really returned for its
fingerprint (captured live via fpcalc + api.acoustid.org). 138 tracks:
Hiroyuki Sawano's Attack on Titan scores (romaji tags vs MusicBrainz's kanji
credit 澤野弘之, ASCII-mangled OST titles like 'Shingeki Pf - Adlib - B 20130218
Kyojin', bracket-credit forms '<Vocal: mpi>'), PianoPrinceOfAnime's epic-cover
catalogue, Michael Jackson remasters, Justin Bieber, James Brown.

The property under test is the one that matters to a user: a file that IS what
it claims must never be quarantined. Every row here is a correct file, so no
row may come back FAIL.

Cross-script artist credits are bridged by the alias provider, exactly as
``core/acoustid_verification`` wires it in production. The map below is a static
stand-in for the live MusicBrainz lookup so the test needs no network.
"""

import pytest

from core.matching.audio_verification import Decision, evaluate, normalize


_ALIASES = {
    'hiroyuki sawano': ['澤野弘之', 'Sawano Hiroyuki', 'SawanoHiroyuki[nZk]'],
    'michael jackson': ['マイケル・ジャクソン'],
}


def _aliases_for(artist):
    return lambda: _ALIASES.get((artist or '').strip().lower(), [])


# (expected_title, expected_artist, [(acoustid_title, acoustid_artist), ...], score)
_REAL_LOOKUPS = [
    ('2Volt', 'Hiroyuki Sawano',
     [('2Volt', '澤野弘之')], 0.99),
    ('2chijou', 'Hiroyuki Sawano',
     [('2chi城', '澤野弘之')], 0.99),
    ('APETITAN', 'Hiroyuki Sawano',
     [('APETITAN', '澤野弘之')], 0.99),
    ('Aots2m #1', 'Hiroyuki Sawano',
     [('AOTs2M他1', '澤野弘之')], 0.99),
    ('Aots2m #2', 'Hiroyuki Sawano',
     [('AOTs2M他2', '澤野弘之')], 1.0),
    ('Aots2m #3', 'Hiroyuki Sawano',
     [('AOTs2M他3', '澤野弘之')], 1.0),
    ('Aots2m #4', 'Hiroyuki Sawano',
     [('AOTs2M他4', '澤野弘之')], 1.0),
    ('Army-Attack', 'Hiroyuki Sawano',
     [('army⇒G♂', '澤野弘之')], 0.98),
    ('Attack on D', 'Hiroyuki Sawano',
     [('attack音D', '澤野弘之')], 1.0),
    ('Attack on Titan', 'Hiroyuki Sawano',
     [('ətˈæk 0N tάɪtn', '澤野弘之 <Vocal: MIKA KOBAYASHI>'), ('(intro) Attack on Titan', '小林未郁')], 0.99),
    ('Barricades', 'Hiroyuki Sawano',
     [('Barricades', '澤野弘之')], 0.99),
    ('Bauklotze', 'Hiroyuki Sawano',
     [('Bauklötze', '澤野弘之 <Vocal: MIKA KOBAYASHI>')], 0.98),
    ('Call Your Name', 'Hiroyuki Sawano',
     [('Call your name', '澤野弘之 <Vocal: mpi & CASG (Caramel Apple Sound Gadget)>')], 0.99),
    ('Call of Silence', 'Hiroyuki Sawano',
     [('Call of Silence', '澤野弘之')], 1.0),
    ('Counter Attack-Mankind', 'Hiroyuki Sawano',
     [('cóunter・attàck-mˈænkάɪnd', '澤野弘之')], 0.98),
    ('DOA', 'Hiroyuki Sawano',
     [('DOA', '澤野弘之 <Vocal: AIMEE BLACKSCHLEGER>')], 0.99),
    ('E.M.A', 'Hiroyuki Sawano',
     [('E・M・A', '澤野弘之')], 0.97),
    ('EMAymniam', 'Hiroyuki Sawano',
     [('EMAymniam', '澤野弘之')], 0.96),
    ('Eye-Water', 'Hiroyuki Sawano',
     [('eye-water', '澤野弘之')], 0.98),
    ('Omake-Pfadlib', 'Hiroyuki Sawano',
     [('omake-pfadlib', '澤野弘之')], 0.97),
    ('Rittaikidou', 'Hiroyuki Sawano',
     [('立body機motion', '澤野弘之')], 0.98),
    ('Shingeki Gt 20130218 Kyojin', 'Hiroyuki Sawano',
     [('進撃gt20130218巨人', '澤野弘之'), ('eye-water', '澤野弘之')], 0.94),
    ('Shingeki Pf - Adlib - B 20130218 Kyojin', 'Hiroyuki Sawano',
     [('Vogel im Käfig', '澤野弘之 <Vocal: Cyua>'), ('進撃pf-adlib-b20130218巨人', '澤野弘之')], 0.97),
    ('Shingeki Pf - Adlib - C 20130218 Kyojin', 'Hiroyuki Sawano',
     [('進撃pf-adlib-c20130218巨人', '澤野弘之'), ('凸】♀】♂】←巨人', '澤野弘之')], 0.96),
    ('Shingeki Pf - Medley 20130629 Kyojin', 'Hiroyuki Sawano',
     [('巨♀〜9地区', '澤野弘之'), ('進撃pf-medley20130629巨人', '澤野弘之')], 0.99),
    ('Shingeki Pf 20130218 Kyojin', 'Hiroyuki Sawano',
     [('The Reluctant Heroes', '澤野弘之 <Vocal: mpi>'), ('進撃pf20130218巨人', '澤野弘之')], 0.95),
    ('Shingeki St - Hrn - Gt 20130629 Kyojin', 'Hiroyuki Sawano',
     [('ətˈæk 0N tάɪtn', '澤野弘之 <Vocal: MIKA KOBAYASHI>'), ('進撃st-hrn-gt20130629巨人', '澤野弘之')], 0.99),
    ('Shingeki St - Hrn- Egt 20130629 Kyojin', 'Hiroyuki Sawano',
     [('ətˈæk 0N tάɪtn', '澤野弘之 <Vocal: MIKA KOBAYASHI>'), ('進撃st-hrn-egt20130629巨人', '澤野弘之')], 0.97),
    ('Shingeki St 20130629 Kyojin', 'Hiroyuki Sawano',
     [('進撃st20130629巨人', '澤野弘之'), ('巨♀〜9地区', '澤野弘之')], 0.99),
    ('Shingeki Vn - Pf 20130524 Kyojin', 'Hiroyuki Sawano',
     [('進撃vn-pf20130524巨人', '澤野弘之'), ('army⇒G♂', '澤野弘之')], 0.98),
    ('So ist es immer', 'Hiroyuki Sawano',
     [('So ist es immer', '澤野弘之')], 1.0),
    ('TWO-lives', 'Hiroyuki Sawano',
     [('TWO-lives', '澤野弘之')], 0.97),
    ('The Reluctant Heroes', 'Hiroyuki Sawano',
     [('The Reluctant Heroes', '澤野弘之 <Vocal: mpi>')], 0.99),
    ('The Reluctant Heroes <MODv>', 'Hiroyuki Sawano',
     [('The Reluctant Heroes', '澤野弘之 <Vocal: mpi>')], 0.99),
    ('TheWeightOfLives', 'Hiroyuki Sawano',
     [('TheWeightOfLives', '澤野弘之')], 0.97),
    ('Titan♀～9chiku', 'Hiroyuki Sawano',
     [('巨♀〜9地区', '澤野弘之')], 0.98),
    ('Vogel Im Kafig', 'Hiroyuki Sawano',
     [('Vogel im Käfig', '澤野弘之 <Vocal: Cyua>')], 1.0),
    ('Xl-Tt', 'Hiroyuki Sawano',
     [('XL-TT', '澤野弘之')], 0.95),
    ('YAMANAIAME', 'Hiroyuki Sawano',
     [('YAMANAIAME', '澤野弘之'), ('YAMANAIAME (Instrumental)', '澤野弘之')], 0.99),
    ('YAMANAIAME <FMv>', 'Hiroyuki Sawano',
     [('YAMANAIAME', '澤野弘之'), ('YAMANAIAME (Instrumental)', '澤野弘之')], 0.99),
    ('YouSeeBIGGIRL/T:T', 'Hiroyuki Sawano',
     [('YouSeeBIGGIRL/T:T', '澤野弘之')], 0.97),
    ('son2seaVer', 'Hiroyuki Sawano',
     [('son2seaVer', '澤野弘之')], 0.99),
    ('theDOGS', 'Hiroyuki Sawano',
     [('theDOGS', '澤野弘之'), ('theDOGS (Instrumental)', '澤野弘之')], 0.99),
    ('ymniam-MKorch', 'Hiroyuki Sawano',
     [('ymniam-MKorch', '澤野弘之')], 0.98),
    ('ymniam-orch', 'Hiroyuki Sawano',
     [('ymniam-orch (sm2_Final#2)', '澤野弘之')], 0.97),
    ('凸】♀】♂】←Titan', 'Hiroyuki Sawano',
     [('凸】♀】♂】←巨人', '澤野弘之')], 0.96),
    ('405', 'Justin Bieber',
     [('405', 'Justin Bieber')], 0.99),
    ('405', 'Justin Bieber',
     [('405', 'Justin Bieber')], 0.97),
    ('ALL I CAN TAKE', 'Justin Bieber',
     [('ALL I CAN TAKE', 'Justin Bieber')], 1.0),
    ('ALL I CAN TAKE', 'Justin Bieber',
     [('ALL I CAN TAKE', 'Justin Bieber')], 0.98),
    ('ALL THE WAY', 'Justin Bieber',
     [('ALL THE WAY', 'Justin Bieber')], 0.97),
    ('BAD HONEY', 'Justin Bieber',
     [('BAD HONEY', 'Justin Bieber')], 0.94),
    ('BETTER MAN', 'Justin Bieber',
     [('BETTER MAN', 'Justin Bieber')], 0.92),
    ('BUTTERFLIES', 'Justin Bieber',
     [('BUTTERFLIES', 'Justin Bieber')], 0.99),
    ('BUTTERFLIES', 'Justin Bieber',
     [('BUTTERFLIES', 'Justin Bieber')], 0.99),
    ('DADZ LOVE', 'Justin Bieber',
     [('DADZ LOVE', 'Justin Bieber & Lil B')], 0.97),
    ('DADZ LOVE', 'Justin Bieber',
     [('DADZ LOVE', 'Justin Bieber & Lil B')], 0.97),
    ('DAISIES', 'Justin Bieber',
     [('DAISIES', 'Justin Bieber'), ('DAISIES', 'Justin Bieber'), ('Daisies', 'Justin Bieber')], 0.97),
    ('DAISIES', 'Justin Bieber',
     [('DAISIES', 'Justin Bieber'), ('DAISIES', 'Justin Bieber'), ('Daisies', 'Justin Bieber')], 0.98),
    ('DEVOTION', 'Justin Bieber',
     [('DEVOTION', 'Justin Bieber & Dijon')], 0.99),
    ('DEVOTION', 'Justin Bieber',
     [('DEVOTION', 'Justin Bieber & Dijon')], 0.99),
    ("DON'T WANNA", 'Justin Bieber',
     [('DON’T WANNA', 'Justin Bieber & Bakar')], 0.96),
    ('DOTTED LINE', 'Justin Bieber',
     [('DOTTED LINE', 'Justin Bieber')], 0.97),
    ('EVERYTHING HALLELUJAH', 'Justin Bieber',
     [('EVERYTHING HALLELUJAH', 'Justin Bieber')], 0.97),
    ('EYE CANDY', 'Justin Bieber',
     [('EYE CANDY', 'Justin Bieber')], 0.98),
    ('FIRST PLACE', 'Justin Bieber',
     [('FIRST PLACE', 'Justin Bieber')], 1.0),
    ('FIRST PLACE', 'Justin Bieber',
     [('FIRST PLACE', 'Justin Bieber')], 0.98),
    ('FORGIVENESS', 'Justin Bieber',
     [('FORGIVENESS', 'Marvin Winans')], 0.99),
    ('FORGIVENESS', 'Justin Bieber',
     [('FORGIVENESS', 'Marvin Winans')], 0.98),
    ('GLORY VOICE MEMO', 'Justin Bieber',
     [('GLORY VOICE MEMO', 'Justin Bieber')], 0.97),
    ('GLORY VOICE MEMO', 'Justin Bieber',
     [('GLORY VOICE MEMO', 'Justin Bieber')], 0.99),
    ('GO BABY', 'Justin Bieber',
     [('GO BABY', 'Justin Bieber')], 0.96),
    ('I DO', 'Justin Bieber',
     [('I DO', 'Justin Bieber')], 0.97),
    ("I THINK YOU'RE SPECIAL", 'Justin Bieber',
     [("I THINK YOU'RE SPECIAL", 'Justin Bieber & Tems')], 0.99),
    ('LOVE SONG', 'Justin Bieber',
     [('LOVE SONG', 'Justin Bieber')], 0.97),
    ("LYIN'", 'Justin Bieber',
     [('LYIN’', 'Justin Bieber')], 0.99),
    ('MOTHER IN YOU', 'Justin Bieber',
     [('MOTHER IN YOU', 'Justin Bieber')], 0.97),
    ('MOVING FAST', 'Justin Bieber',
     [('MOVING FAST', 'Justin Bieber')], 0.97),
    ('NEED IT', 'Justin Bieber',
     [('NEED IT', 'Justin Bieber')], 0.97),
    ('OH MAN', 'Justin Bieber',
     [('OH MAN', 'Justin Bieber')], 0.97),
    ('OPEN UP YOUR HEART', 'Justin Bieber',
     [('OPEN UP YOUR HEART', 'Justin Bieber & Eddie Benjamin')], 0.97),
    ('PETTING ZOO', 'Justin Bieber',
     [('PETTING ZOO', 'Justin Bieber')], 0.98),
    ('POPPIN’ MY S***', 'Justin Bieber',
     [('POPPIN’ MY S***', 'Justin Bieber & Hurricane Chris')], 0.98),
    ('SAFE SPACE', 'Justin Bieber',
     [('SAFE SPACE', 'Justin Bieber & Lil B')], 0.97),
    ('SOULFUL', 'Justin Bieber',
     [('SOULFUL', 'Justin Bieber & Druski'), ('SOULFUL', 'Justin Bieber & Druski')], 0.99),
    ('SOULFUL', 'Justin Bieber',
     [('SOULFUL', 'Justin Bieber & Druski'), ('SOULFUL', 'Justin Bieber & Druski')], 0.99),
    ('SPEED DEMON', 'Justin Bieber',
     [('SPEED DEMON', 'Justin Bieber')], 1.0),
    ('STANDING ON BUSINESS', 'Justin Bieber',
     [('STANDING ON BUSINESS', 'Justin Bieber & Druski'), ('STANDING ON BUSINESS', 'Justin Bieber & Druski')], 0.96),
    ('STANDING ON BUSINESS', 'Justin Bieber',
     [('STANDING ON BUSINESS', 'Justin Bieber & Druski'), ('STANDING ON BUSINESS', 'Justin Bieber & Druski')], 0.99),
    ('STORY OF GOD', 'Justin Bieber',
     [('STORY OF GOD', 'Justin Bieber')], 0.97),
    ('SWAG', 'Justin Bieber',
     [('SWAG', 'Justin Bieber, Cash Cobain & Eddie Benjamin'), ('SWAG', 'Justin Bieber, Cash Cobain & Eddie Benjamin')], 0.97),
    ('SWAG', 'Justin Bieber',
     [('SWAG', 'Justin Bieber, Cash Cobain & Eddie Benjamin'), ('SWAG', 'Justin Bieber, Cash Cobain & Eddie Benjamin')], 0.97),
    ('SWEET SPOT', 'Justin Bieber',
     [('SWEET SPOT', 'Justin Bieber & Sexyy Red'), ('SWEET SPOT', 'Justin Bieber & Sexyy Red')], 1.0),
    ('SWEET SPOT', 'Justin Bieber',
     [('SWEET SPOT', 'Justin Bieber & Sexyy Red'), ('SWEET SPOT', 'Justin Bieber & Sexyy Red')], 0.99),
    ('THERAPY SESSION', 'Justin Bieber',
     [('THERAPY SESSION', 'Justin Bieber & Druski'), ('THERAPY SESSION', 'Justin Bieber & Druski')], 0.99),
    ('THERAPY SESSION', 'Justin Bieber',
     [('THERAPY SESSION', 'Justin Bieber & Druski'), ('THERAPY SESSION', 'Justin Bieber & Druski')], 0.99),
    ('THINGS YOU DO', 'Justin Bieber',
     [('THINGS YOU DO', 'Justin Bieber')], 0.96),
    ('THINGS YOU DO', 'Justin Bieber',
     [('THINGS YOU DO', 'Justin Bieber')], 0.99),
    ('TOO LONG', 'Justin Bieber',
     [('TOO LONG', 'Justin Bieber'), ('TOO LONG', 'Justin Bieber')], 0.97),
    ('TOO LONG', 'Justin Bieber',
     [('TOO LONG', 'Justin Bieber'), ('TOO LONG', 'Justin Bieber')], 0.97),
    ('WALKING AWAY', 'Justin Bieber',
     [('WALKING AWAY', 'Justin Bieber'), ('WALKING AWAY', 'Justin Bieber')], 0.81),
    ('WALKING AWAY', 'Justin Bieber',
     [('WALKING AWAY', 'Justin Bieber'), ('WALKING AWAY', 'Justin Bieber')], 0.81),
    ('WAY IT IS', 'Justin Bieber',
     [('WAY IT IS', 'Justin Bieber & Gunna')], 0.97),
    ('WAY IT IS', 'Justin Bieber',
     [('WAY IT IS', 'Justin Bieber & Gunna')], 0.99),
    ("WHEN IT'S OVER", 'Justin Bieber',
     [('WHEN IT’S OVER', 'Justin Bieber')], 0.97),
    ('WITCHYA', 'Justin Bieber',
     [('WITCHYA', 'Justin Bieber')], 0.97),
    ('YUKON', 'Justin Bieber',
     [('YUKON', 'Justin Bieber')], 0.97),
    ('YUKON', 'Justin Bieber',
     [('YUKON', 'Justin Bieber')], 0.99),
    ('ZUMA HOUSE', 'Justin Bieber',
     [('ZUMA HOUSE', 'Justin Bieber')], 0.97),
    ('ZUMA HOUSE', 'Justin Bieber',
     [('ZUMA HOUSE', 'Justin Bieber')], 0.99),
    ('Baby Be Mine', 'Michael Jackson',
     [('Monkey Business', 'Michael Jackson'), ('Baby Be Mine', 'Michael Jackson'), ('One Day in Your Life', 'Michael Jackson')], 0.96),
    ('Black or White', 'Michael Jackson',
     [('Black or White (single version)', 'Michael Jackson'), ('Black or White', 'Michael Jackson'), ('Black or White', 'Michael Jackson')], 0.97),
    ('Blood On The Dance Floor X Dangerous (The White Panda Mash-Up)', 'Michael Jackson',
     [('Blood on the Dance Floor X Dangerous (The White Panda Mash‐Up)', 'Michael Jackson')], 0.89),
    ('Blood on the Dance Floor', 'Michael Jackson',
     [('Blood on the Dance Floor', 'Michael Jackson'), ('Blood on the Dance Floor', 'Michael Jackson'), ('The Finer Things', 'Steve Winwood')], 0.98),
    ("Can't Let Her Get Away", 'Michael Jackson',
     [("Can't Let Her Get Away", 'Michael Jackson'), ('Can’t Let Her Get Away', 'Michael Jackson')], 0.97),
    ('Dangerous', 'Michael Jackson',
     [('Dangerous', 'Michael Jackson'), ('You Can’t Win', 'Michael Jackson'), ('Earth Song', 'Michael Jackson')], 0.98),
    ('Dangerous', 'Michael Jackson',
     [('Dangerous', 'Michael Jackson'), ('You Can’t Win', 'Michael Jackson'), ('Earth Song', 'Michael Jackson')], 0.98),
    ('Dirty Diana (2012 Remaster)', 'Michael Jackson',
     [('Dirty Diana', 'Michael Jackson'), ('Dirty Diana', 'Michael Jackson'), ('Dirty Diana', 'Michael Jackson')], 0.98),
    ('Ghosts', 'Michael Jackson',
     [('Ghost', 'Michael Jackson'), ('Jealous Ghost', 'Michael Jackson'), ('Ghosts', 'Michael Jackson')], 0.97),
    ('Give In to Me', 'Michael Jackson',
     [("Give In to Me (Michael Jackson's Vision)", 'Michael Jackson'), ('Give in to Me', 'Michael Jackson'), ('Give In to Me', 'Michael Jackson')], 0.98),
    ('Heal the World', 'Michael Jackson',
     [('Heal the World', 'Michael Jackson'), ('Heal the World (album version)', 'Michael Jackson'), ('Heal the World', 'Michael Jackson')], 0.92),
    ('In the Closet', 'Michael Jackson',
     [("In the Closet (Michael Jackson's Vision)", 'Michael Jackson'), ('Heal the World', 'Michael Jackson'), ('In the Closet', 'Michael Jackson')], 0.95),
    ('Jam', 'Michael Jackson',
     [("Don't Stop Till You Get Enough", 'Michael Jackson'), ('Jam', 'Michael Jackson'), ('Jam', 'Michael Jackson')], 0.95),
    ('Keep the Faith', 'Michael Jackson',
     [('Keep the Faith', 'Michael Jackson'), ('Keep the Faith', 'Michael Jackson'), ('Keep the Faith', 'Michael Jackson')], 0.98),
    ('Leave Me Alone (2012 Remaster)', 'Michael Jackson',
     [('Leave Me Alone', 'Michael Jackson'), ('Leave Me Alone', 'Michael Jackson'), ('Leave Me Alone', 'Michael Jackson')], 0.98),
    ('Remember the Time', 'Michael Jackson',
     [('Come Together', 'Michael Jackson'), ('She Drives Me Wild', 'Michael Jackson'), ('Remember the Time', 'Julian Vaughn')], 0.97),
    ('Scream', 'Michael Jackson',
     [('Scream', 'Blue Train'), ('Scream', 'Michael Jackson'), ('Scream (clean album version)', 'Michael Jackson & Janet Jackson')], 0.97),
    ('She Drives Me Wild', 'Michael Jackson',
     [('She Drives Me Wild', 'Michael Jackson'), ('The Girl Is Mine', 'Michael Jackson with Paul McCartney')], 0.96),
    ('Threatened', 'Michael Jackson',
     [('Threatened', 'Michael Jackson'), ('Threatened', 'Michael Jackson'), ('Threatened', 'Michael Jackson')], 0.99),
    ('Torture', 'Michael Jackson',
     [('Torture', 'The Jacksons'), ('Torture', 'The Jacksons'), ('Torture', 'The Jacksons')], 0.96),
    ('Unbreakable', 'Michael Jackson',
     [('Ben', 'Michael Jackson'), ('Unbreakable', 'Michael Jackson'), ('Unbreakable', 'Michael Jackson')], 0.99),
    ("Wanna Be Startin' Somethin'", 'Michael Jackson',
     [('Wanna Be Startin’ Somethin’', 'Michael Jackson'), ('Wanna Be Startin’ Somethin’', 'Michael Jackson'), ('Thriller', 'Michael Jackson')], 1.0),
    ('Who Is It', 'Michael Jackson',
     [('Who Is It', 'Michael Jackson'), ('Who Is It', 'Michael Jackson'), ('Who Is It', 'Michael Jackson')], 0.97),
    ('Why You Wanna Trip on Me', 'Michael Jackson',
     [('Why You Wanna Trip on Me', 'Michael Jackson')], 0.97),
    ('Will You Be There', 'Michael Jackson',
     [('Will You Be There', 'Michael Jackson'), ('Will You Be There', 'Michael Jackson'), ('Will You Be There (album version)', 'Michael Jackson')], 0.96),
    ('Xscape', 'Michael Jackson',
     [('Xscape', 'Michael Jackson'), ('Xscape', 'Michael Jackson')], 0.99),
    ('Memory Reboot', 'VØJ',
     [('Memory Reboot', 'VØJ & Narvent')], 1.0),
    ('Memory Reboot', 'VØJ',
     [('Memory Reboot', 'VØJ & Narvent')], 0.98),
]


@pytest.mark.parametrize("title,artist,recordings,score", _REAL_LOOKUPS)
def test_a_correct_file_is_never_quarantined(title, artist, recordings, score):
    out = evaluate(
        title, artist,
        [{'title': t, 'artist': a} for t, a in recordings],
        fingerprint_score=score,
        aliases_provider=_aliases_for(artist),
    )
    assert out.decision != Decision.FAIL, (
        f"{title!r} by {artist!r} was quarantined against {out.matched_title!r} "
        f"by {out.matched_artist!r} (title_sim={out.title_sim:.2f}, "
        f"artist_sim={out.artist_sim:.2f}): {out.reason}"
    )


# --- the one genuinely ambiguous row in the capture ---

_BOUNDARY = [
    ("Somebody's Watching Me (Single Version)", 'Michael Jackson',
     [('Somebody’s Watching Me', 'Rockwell'), ("Somebody's Watching Me (Single Version)", 'Rockwell'), ('Somebody’s Watching Me', 'Gene Rockwell')], 0.98),
]


@pytest.mark.parametrize("title,artist,recordings,score", _BOUNDARY)
def test_a_foreign_cover_of_the_same_title_is_not_a_pass(title, artist, recordings, score):
    """AcoustID answers this MJ fingerprint with a metal cover by Warmen. The
    titles are identical, the artists are not related, so the one thing the
    core must not do is call it verified. FAIL or SKIP are both defensible —
    production's live alias lookup lands on SKIP, this static map on FAIL."""
    out = evaluate(
        title, artist,
        [{'title': t, 'artist': a} for t, a in recordings],
        fingerprint_score=score,
        aliases_provider=_aliases_for(artist),
    )
    assert out.decision != Decision.PASS


# --- CJK identity must survive normalization ---
#
# `normalize` keeps word characters of every script, so a Japanese/Korean title
# must come out comparable rather than empty. An empty normalization scores 0.0
# against everything, which is a SKIP for a file nothing is wrong with.

_CJK_TITLES = [
    '"Attack On Titan" Season 3 (Original Soundtrack) = 「進撃の巨人」Season 3 オリジナルサウンドトラック',
    '"Attack on Titan" Original Soundtrack II = 「進撃の巨人」オリジナルサウンドトラックII',
    '86―エイティシックス― オリジナル・サウンドトラック',
    'AOTs2M他1',
    'AOTs2M他2',
    'AOTs2M他3',
    'AOTs2M他4',
    'Ashes on The Fire (進撃の巨人 The Final Season Original Soundtrack) - Single',
    'Dream Diver (feat. 巡音ルカ)',
    'ERENthe標',
    'E・M・A',
    'Feeling Good (Live典藏)',
    'Home (Live典藏)',
    'Invisible (feat. 雪歌ユフ)',
    'LilaS (feat. たかはしほのか) - Single',
    'MYTH & ROID Concept mini album 〈Episode 2〉『VERDE』',
    'MYTH & ROID ベストアルバム「MUSEUM-THE BEST OF MYTH & ROID-」',
    'Make It Right (feat. 滲音かこい)',
    'Might+U 〜Live Special Arrange〜＜My Hero Academia＞',
    'Music Box (feat. 初音ミク)',
    'My War (Attack on Titan) - 僕の戦争',
    'My War (Attack on Titan) - 僕の戦争 - Single',
    'Nightmare (feat. 破壊音マイコ)',
    'Puzzle Heart (feat. 初音ミク)',
    'TVアニメ「Re:ゼロから始める異世界生活」後期オープニングテーマ「Paradisus-Paradoxum」',
    'TVアニメ「オーバーロード」エンディングテーマ「L.L.L.」',
    'TVアニメ「キングダム」第4シリーズ Original Sound Track',
    'TVアニメ「ブブキ・ブランキ」エンディングテーマ「ANGER/ANGER」',
    'TVアニメ「七つの大罪 憤怒の審判」オリジナル・サウンドトラック',
    'TVアニメ「七つの大罪 神々の逆鱗」オリジナル・サウンドトラック',
    'TVアニメ「進撃の巨人 The Final Season」 Original Sound Track Complete Album',
    'TVアニメ「進撃の巨人」 The Final Season Original Soundtrack',
    'TVアニメ「進撃の巨人」 The Final Season Original Soundtrack 02',
    'TVアニメ「進撃の巨人」 The Final Season Original Soundtrack 03 - EP',
    'TVアニメ「進撃の巨人」Season 2 オリジナルサウンドトラック',
    'TVアニメ「進撃の巨人」オリジナルサウンドトラック',
    'Take Me Home，Country Roads (Live典藏)',
    'Thunderbolt Fantasy 東離劍遊紀 オリジナルサウンドトラック',
    'Thunderbolt Fantasy 東離劍遊紀2 オリジナルサウンドトラック',
    'attack音 & DERENthe標 (From "Shingeki no Kyojin 2")',
    'attack音D',
    'cóunter・attàck-mˈænkάɪnd',
    '「CRISIS 公安機動捜査隊特捜班」ORIGINAL SOUNDTRACK/BONUS TRACK',
    '「プロメア」オリジナルサウンドトラック',
    '「進撃の巨人」Season3 オリジナルサウンドトラック',
    'もうどうなってもいいや - Single',
    'アルドノア・ゼロ オリジナル・サウンドトラック',
    'キルラキル コンプリートサウンドトラック',
    'キルラキルオリジナルサウンドトラック',
    'ギルティクラウン オリジナルサウンドトラック',
    '一个人跳舞 (Live)',
    '一个人跳舞 (Live典藏)',
    '七つの大罪 オリジナル・サウンドトラック',
    '七つの大罪 オリジナル・サウンドトラック 2',
    '二千年... 若しくは... 二万年後の君へ・・・ - Single',
    '侠客令 (Live)',
    '侠客令 (Live典藏)',
    '俺だけレベルアップな件 Original Soundtrack',
    '俺だけレベルアップな件 Season2 -Arise from the Shadow- Original Soundtrack',
    '僕の戦争 - Single',
    '凸】♀】♂】←Titan',
    '劇場版 七つの大罪 天空の囚われ人 オリジナル・サウンドトラック',
    '劇場版「進撃の巨人」前編~紅蓮の弓矢~エンディングテーマ YAMANAIAME produced by 澤野弘之',
    '劇場版「進撃の巨人」後編~自由の翼~エンディングテーマ theDOGS produced by 澤野弘之 - EP',
    '悪魔の子 - Single',
    '最後の巨人 - Single',
    '未来的主人翁 (Live)',
    '未来的主人翁 (Live典藏)',
    '欢乐时光：派对狂欢中的平静时刻',
    '歌手2025 第6期 (Live)',
    '甲鉄城のカバネリ COMPLETE SOUNDTRACK',
    '甲鉄城のカバネリ ORIGINAL SOUNDTRACK',
    '群青のファンファーレ オリジナル・サウンドトラック',
    '自由への進撃 - Single',
    '進撃gt20130218巨人',
    '進撃pf-adlib-b20130218巨人',
    '進撃pf-adlib-c20130218巨人',
    '進撃pf-medley20130629巨人',
    '進撃pf20130218巨人',
    '進撃st-hrn-egt20130629巨人',
    '進撃st-hrn-gt-pf20130629巨人',
    '進撃st-hrn-gt20130629巨人',
    '進撃st20130629巨人',
    '進撃vc-pf20130218巨人',
    '進撃vn-pf20130524巨人',
    '進撃の軌跡',
    '雪を聴く夜',
    '青の祓魔師 オリジナル・サウンドトラック 2024-25',
    '青の祓魔師 オリジナル・サウンドトラック I',
    '青の祓魔師 オリジナル・サウンドトラック II',
    '青の祓魔師 京都不浄王篇 オリジナル・サウンドトラック',
    '青の祓魔師 劇場版 オリジナル・サウンドトラック',
]


@pytest.mark.parametrize("title", _CJK_TITLES)
def test_cjk_titles_normalize_to_something_comparable(title):
    assert normalize(title), f"{title!r} normalized to an empty string"
