"""The dash-tail rule against the REAL catalogue.

Every distinct ``' - <tail>'`` shape found in the 13,728 track/album titles of a
live SoulSync library (Deezer + iTunes + MusicBrainz caches, a large anime/OST
and Japanese-artist section, Michael Jackson, James Brown, Justin Bieber,
Hiroyuki Sawano, PianoPrinceOfAnime). Synthetic examples cannot produce the
shapes a real catalogue does — 'Inst Ver.', 'Epic Cover', 'Lord Of The
Mysteries EP 13', 'Shingeki Pf - Adlib - B 20130218 Kyojin' — and every one of
those is a decision this rule has to get right.

The second element of each pair is a real title the tail was taken from, so a
failure names the actual row that would break.
"""

import pytest

from core.text.title_match import is_trailing_version_qualifier


# --- tails the rule must drop: they annotate a version, not a song ---

_VERSION_TAILS = [
    ('a cappella', 'the boy is mine – a cappella (a cappella)'),
    ('c&n project mix', 'Dinata Dinata - C&N Project Mix'),
    ('chill ver.', "Cat's Eye Main Theme - Chill Ver."),
    ('cover', '1106 TYBW CH united - Cover'),
    ('dance mixes', 'Above and Beyoncé - Dance Mixes'),
    ('delta heavy remix', "Don't You Want Me - Delta Heavy Remix"),
    ('emotional cover', 'DARK ARIA <LV.2> (PIANO VERSION) - Solo Leveling S2 - Emotional Cover'),
    ('emotional version', 'HIS THEME (2025 Ver.) - Undertale - Emotional Version'),
    ('ep', '#tBt - EP'),
    ('epic cover', '10th S-RANK HUNTER - aikari - Solo Leveling S2 - Epic Cover'),
    ('epic version', 'AIZO - Jujutsu Kaisen S3 Opening Song - Epic Version'),
    ('extended', 'How Does It Feel - Extended'),
    ('extended mix', 'Edge of Desire - Extended Mix'),
    ('extended version', 'Dinata Dinata - Extended Version'),
    ('from the first take', 'Kataomoi - From THE FIRST TAKE'),
    ('inst ver.', "Cat's Eye Main Theme - Inst Ver."),
    ('instrumental', 'HEADSHOT - Instrumental'),
    ('instrumental ver.', 'I really want to stay at your house - EPIC VERSION - Instrumental ver.'),
    ('jonas s. club mix', 'Dinata Dinata - Jonas S. Club Mix'),
    ('kanye west remix', 'Runaway Love - Kanye West Remix'),
    ('karaoke version', 'Before My Body is Dry -Karaoke Version'),
    ('live 2011', 'Bring Me Home - Live 2011'),
    ('live american broadcast', 'Bee Gees - Lay it On Me - Live American Broadcast (Live)'),
    ('live at the apollo 1995', 'The Great James Brown - Live At The Apollo 1995'),
    ('mha arr ver.', 'Sixth Magnitude Star - MHA Arr Ver. (From "My Hero Academia" 7th Season)'),
    ('michael jackson mix', 'Funkot Dance! - Sexy Hyper Dance Party - Michael Jackson Mix'),
    ('moonlit ver.', "Cat's Eye Main Theme - Moonlit Ver."),
    ('movie ver.', 'Barricades - Movie ver. (Instrumental)'),
    ('not without friends extended remix', "Groovejet (If This Ain't Love) - not without friends Extended Remix"),
    ('orchestra version', 'S_Team -Orchestra Version'),
    ('original soundtrack ep', 'Fate/strange Fake -Whispers of Dawn- Original Soundtrack EP'),
    ('over slowed', 'Memory Reboot - Over Slowed'),
    ('piano & orchestra version', 'WISHING - To Be Hero X Ep 9 OST - Piano & Orchestra Version'),
    ('radio edit', 'Dinata Dinata - Radio Edit'),
    ('rain version', 'Vogel im Käfig (From "Attack on Titan") - Rain Version'),
    ('remix', 'the boy is mine – Remix (Remix)'),
    ('remix a cappella', 'the boy is mine – Remix a cappella'),
    ('remixes', 'Can You Feel It - Remixes'),
    ('single', '10,000 Hours (Acoustic) - Single'),
    ('slowed', 'GLOW - Slowed'),
    ('slowed down version', 'School Rooftop - Slowed Down Version'),
    ('soft piano version', 'MY COLOR - To Be Hero X Ep 10 OST - Soft Piano Version'),
    ('sped up', 'GLOW - Sped Up'),
    ('super slowed', 'GLOW - Super Slowed'),
    ('the essential mixes', '12" Masters - The Essential Mixes'),
    ('the remixes', 'Last Christmas - The Remixes'),
    ('trailer version', 'Superman Theme - Trailer Version (Epic Version)'),
    ('ultra slowed', 'Via Lactea - Ultra Slowed'),
    ('version', 'Before My Body Is Dry -[nZk] Version'),
    ('version instrumental', 'Before My Body Is Dry -[nZk] Version Instrumental'),
]


@pytest.mark.parametrize("tail,example", _VERSION_TAILS)
def test_catalogue_version_tails_are_dropped(tail, example):
    assert is_trailing_version_qualifier(tail) is True, (
        f"{tail!r} is a version tag (from {example!r}) but the rule kept it"
    )


# --- tails the rule must KEEP: they are the song, a subtitle, or an episode ---

_REAL_TAILS = [
    ("'50s", "From The Vaults -'50s"),
    ('2 of 2', 'The 20/20 Experience - 2 of 2 (Deluxe)'),
    ('3rd season collection pt.2', 'RE:ZERO-STARTING LIFE IN ANOTHER WORLD- 3RD SEASON COLLECTION Pt.2'),
    ('4n', '96-6Ki4- 4N'),
    ('50 años de patria, tradición y navídad', 'Greatest Christmas Hits of the Last Half Century - 50 Años de Patria, Tradición y Navídad (1962-2012) [Original Recordings] [feat. Andy Montanez & Pellin Rodriguez]'),
    ('a cloud of war', 'Inequality - A Cloud of War'),
    ('a happy ending', "Mya's Theme - Wuthering Waves - A Happy Ending (Fan-Made)"),
    ('aemeath', 'Wuthering Waves v3.1 - Story Cinematics - Salvation - Aemeath'),
    ('ai no kigen', 'Genesis of Love - Ai No Kigen'),
    ('attack on titan', 'You See Big Girl - Attack on Titan (Lofi Remix)'),
    ("azik's backstory", "Lord Of Mysteries EP 6 - Azik's Backstory"),
    ('b 20130218 kyojin', 'Shingeki Pf - Adlib - B 20130218 Kyojin'),
    ('bee gees', 'Their Best Tracks - Bee Gees (Live)'),
    ('best of', 'Rhapsody In Blue - Best Of'),
    ('bombing mission', 'Opening - Bombing Mission'),
    ('book i', 'HIStory - PAST, PRESENT AND FUTURE - BOOK I'),
    ('by blade & will', "Chisa's Theme - Wuthering Waves - By Blade & Will (Epic Version)"),
    ('c 20130218 kyojin', 'Shingeki Pf - Adlib - C 20130218 Kyojin'),
    ("captain's theme", "Lord Of Mysteries EP 13 - Captain's Theme"),
    ('cartethyia & fleurdelys', 'Wuthering Waves v2.4 Story Cinematics - Dawn Arrives - Cartethyia & Fleurdelys'),
    ('cartethyia theme', 'Wuthering Waves Resonator Combat Showcase - Cartethyia Theme'),
    ('cour 1', 'Re Zero Season 4 Epic Collection - Cour 1'),
    ('dan da dan s2 ep 10', 'KAIJU APPEARS - Dan Da Dan S2 EP 10 (Epic Version)'),
    ('dan da dan s2 ep 11', 'GREAT KINTA TRANSFORMATION - Dan Da Dan S2 EP 11 (Epic Version)'),
    ('dan da dan s2 ep 12', 'SPACE KAIJU VS GIANT ROBOT - Dan Da Dan S2 EP 12 (Epic Version)'),
    ('dan da dan s2 ep 2', "Evil Eye's Theme - Dan Da Dan S2 EP 2 (Epic Version)"),
    ('dan da dan s2 ep 3', 'Okarun VS Evil Eye - Dan Da Dan S2 EP 3 (Epic Version)'),
    ('dan da dan s2 ep 4', "Momo & Okarun's Theme - Dan Da Dan S2 EP 4 (Epic Version)"),
    ('dan da dan s2 ep 6', 'HUNTING SOUL - Dan Da Dan S2 EP 6 (Epic Version)'),
    ('dan da dan s2 ep 7', 'Evil Eye Hurts Momo - Dan Da Dan S2 EP 7 (Epic Version)'),
    ('dan da dan s2 ep 8', 'Ode to Joy from Symphony No.9 - Dan Da Dan S2 EP 8 (Epic Version)'),
    ('dan da dan s2 ep 9', 'Okarun VS Evil Eye Pt. 2 - Dan Da Dan S2 EP 9 (Epic Version)'),
    ('demon slayer infinity castle arc movie', 'Akaza vs Tanjiro & Giyuu - Demon Slayer Infinity Castle Arc Movie (Epic Version)'),
    ('djalit pejan', 'Madonna - Djalit Pejan'),
    ("don't forget", "Ending Theme - Don't Forget (Version 1)"),
    ('due', 'KINGDOM - DUE'),
    ('egt 20130629 kyojin', 'Shingeki St - Hrn- Egt 20130629 Kyojin'),
    ('el glace frosse', "Elfaria's Theme - El Glace Frosse"),
    ('epic collection', 'Attack on Titan (Season 4) - Epic Collection'),
    ('epic orchestra', 'Nanmonee - Chainsmoker Cat Opening Song - EPIC ORCHESTRA'),
    ('favorite violin encores', 'Isaac Stern: "Humoresque" - Favorite Violin Encores (Expanded Edition)'),
    ('fight theme', 'HEROES vs VILLIANS - To Be Hero X - Fight Theme'),
    ('for a change', 'Otto - For a Change'),
    ('girl gone wild', "Madonna vs. Avicii – Girl Gone Wild (AVICII's UMF Mix)"),
    ('golden wheat dance on the hill', 'Trees Whispers - Golden Wheat Dance On The Hill'),
    ('graduation show', "Aemeath's Theme - Wuthering Waves v3.1 -Resonator Showcase - Graduation Show"),
    ('greatest hits', 'The Bee Gees - Greatest Hits (Live)'),
    ('gt 20130629 kyojin', 'Shingeki St - Hrn - Gt 20130629 Kyojin'),
    ("i'm black and i'm proud", "Finale: Cold Sweat/ I Got The Feeling/ Say It Loud - I'm Black And I'm Proud (Live At Dallas Memorial Auditorium / 1968)"),
    ('ii eno michi', 'Sairai - Ii Eno Michi'),
    ("ince zangwill's theme", "Lord Of Mysteries EP 13 - Ince Zangwill's Theme (Epic Version)"),
    ('inferno', 'ASHES - Inferno'),
    ('interview', 'Bee Gees - Live American Broadcast - Interview (Live)'),
    ('james brown', 'Legenden des Soul - James Brown'),
    ('justin bieber', 'Peaches - Justin Bieber (Remix)'),
    ("kaiju's theme", "Dan Da Dan S2 EP 10 - Kaiju's Theme (Epic Version)"),
    ('ladies and gentlemen introducing mario biondi', 'Intro - Ladies and Gentlemen Introducing Mario Biondi'),
    ('licking stick', 'Licking Stick - Licking Stick'),
    ('lightly we toss the crown theme', 'Wuthering Waves V2.4 Trailer - Lightly We Toss the Crown Theme'),
    ('lives', 'Two - Lives'),
    ('lol brothers', 'Dinata Dinata - LOL Brothers (On A Mission Mix)'),
    ('lord of the mysteries ep 1', 'Moonlight Sonata - Lord Of The Mysteries EP 1 (Epic Version)'),
    ('lord of the mysteries ep 13', "Captain Dunn's Death Theme - Lord Of The Mysteries EP 13 (Epic Version)"),
    ('lord of the mysteries ep 3', 'Klein vs Clown - Lord Of The Mysteries EP 3 (Epic Version)'),
    ('lord of the mysteries ep 4', 'Klein vs Selenia - Lord Of The Mysteries EP 4 (Epic Version)'),
    ('lord of the mysteries ep 6', "Azik's Backstory - Lord Of The Mysteries EP 6 (Epic Version)"),
    ('lord of the mysteries ep 7', 'Klein Unlocks Power - Lord Of The Mysteries EP 7 (Epic Version)'),
    ('lord of the mysteries ep 8', 'Old Neil Plays Moonlight Sonata - Lord Of The Mysteries EP 8 (Epic Version)'),
    ('lord of the mysteries ep 9', "Old Neil's Death Theme - Lord Of The Mysteries EP 9 (Epic Version)"),
    ('medley 20130629 kyojin', 'Shingeki Pf - Medley 20130629 Kyojin'),
    ('melodies of life', 'A Place to Call Home - Melodies of Life (Final Fantasy IX)'),
    ('mkorch', 'Ymniam - Mkorch'),
    ('my hero academia 8th season', 'Bakugo vs All For One - My Hero Academia 8th Season (Epic Version)'),
    ('neil plays moonlight sonata', 'Lord Of Mysteries EP 8 - Neil Plays Moonlight Sonata (Epic Version)'),
    ("neil's death theme", "Lord Of Mysteries EP 9 - Neil's Death Theme (Epic Version)"),
    ('opening song', 'INERETIA - To Be Hero X - OPENING SONG'),
    ('orch', 'Ymniam - Orch'),
    ('original motion picture soundtrack', 'EPiC: Elvis Presley in Concert - Original Motion Picture Soundtrack'),
    ('original soundtrack', 'Solo Leveling Season2 -Arise from the Shadow- Original Soundtrack'),
    ('original soundtrack selected edition vol.1', 'UniteUp! -Uni:Birth- Original Soundtrack Selected Edition vol.1'),
    ('original soundtrack vol.1', 'Ryuzoku -The Blazing Dawn- Original Soundtrack Vol.1'),
    ('pf 20130218 kyojin', 'Shingeki Vc - Pf 20130218 Kyojin'),
    ('pf 20130524 kyojin', 'Shingeki Vn - Pf 20130524 Kyojin'),
    ('pf 20130629 kyojin', 'Shingeki St - Hrn - Gt - Pf 20130629 Kyojin'),
    ('phrolova theme', 'Wuthering Waves 2.5 Trailer - Unfading Melody of Life - Phrolova Theme (Epic Version)'),
    ('pizza song', '500 Years Of Winter - Pizza Song'),
    ('queen of trill', 'Intro- QueeN of Trill'),
    ('scene', 'Capritica IV - Scene'),
    ("smile's death theme", "To Be Hero X EP 22 - Smile's Death Theme (Epic Version)"),
    ('solo leveling season 2 ed', 'UN-APEX - Solo Leveling Season 2 ED (Epic Cover)'),
    ('solo leveling season 2 op', 'ReawakeR - Solo Leveling Season 2 OP (Epic Cover)'),
    ('soundtracks from zelda, final fantasy & more', 'Game Music - Soundtracks from Zelda, Final Fantasy & More'),
    ('static', 'Parrot-y / Volume IV - Static'),
    ('thank you', 'Outro- Thank You'),
    ('thanks at', 'YouSeeBIGGIRL - Thanks AT'),
    ('the apothecary diaries s2 op', 'Hyakka Ryouran - The Apothecary Diaries S2 OP (Epic Cover)'),
    ('the collection', 'My Worlds - The Collection (International Package)'),
    ('the complete gospel recordings', 'Peace In The Valley - The Complete Gospel Recordings'),
    ('the james brown story', 'Get On Up - The James Brown Story (Original Motion Picture Soundtrack)'),
    ('the millennium collection: the best of jackson 5', '20th Century Masters - The Millennium Collection: The Best of Jackson 5'),
    ('the motown solo collection', 'Hello World - The Motown Solo Collection'),
    ('the soundtrack', 'Wicked: For Good – The Soundtrack'),
    ('the universal masters collection', 'Classic - The Universal Masters Collection'),
    ('the untold chapter', 'Bedtime Stories – The Untold Chapter'),
    ('their greatest tracks', 'Bee Gees - Live American Broadcast - Their Greatest Tracks (Live)'),
    ("this girl's in love", "This Guy - This Girl's In Love"),
    ('threnodian boss fight', 'Wuthering Waves 2.7 - Threnodian Boss Fight (Epic Version)'),
    ('to be hero x ep 13', "Luo Li's Theme - To Be Hero X EP 13 (Epic Version)"),
    ('to be hero x ep 15', 'Ghostblade Dinner Scene - To Be Hero X EP 15 (Epic Version)'),
    ('to be hero x ep 16', 'Ghostblade - JEOPARDY - To Be Hero X EP 16 (Epic Version)'),
    ('to be hero x ep 17', 'Big Johnny Transforms - To Be Hero X EP 17 (Epic Version)'),
    ('to be hero x ep 18', 'Little Johnny Theme - GrowL - To Be Hero X EP 18 (Epic Version)'),
    ('to be hero x ep 19', 'E-SOUL & NICE APPEARS - To Be Hero X EP 19 (Epic Version)'),
    ('to be hero x ep 20', "Lou li's Father Death Theme - To Be Hero X EP 20 (Epic Version)"),
    ('to be hero x ep 21', 'Dragon Boy VS SMILE - To Be Hero X EP 21 (Epic Version)'),
    ('to be hero x ep 22', 'SMILE Death Theme - To Be Hero X EP 22 (Epic Version)'),
    ('to be hero x ep 23', 'X Saves AHU - To Be Hero X EP 23 (Epic Version)'),
    ('to be hero x ep 24', 'X vs EVERYONE - To Be Hero X EP 24 (Epic Version)'),
    ('tojima wants to be a masked rider ep 2', 'TACKLE! Kamen Rider - Tojima Wants To Be A Masked Rider EP 2 (Epic Version)'),
    ('tora no moto', 'Amatora - Tora No Moto'),
    ('tribute to passenger', 'Let Her Go - Tribute to Passenger'),
    ('wanna be startin’ somethin’ by michael jackson.', 'Wanna Be Scratching’ Somethin - Wanna Be Startin’ Somethin’ by Michael Jackson.'),
    ('wuthering waves', "Till We Meet Again - Denia's Fan Theme - Wuthering Waves"),
    ('wuthering waves 2.6', 'Iuno Resonator - COMBAT SHOWCASE - Wuthering Waves 2.6 (Epic Version)'),
    ('wuthering waves v3.1', "One Final Promise - Aemeath's Fan Made Theme - Wuthering Waves v3.1"),
    ('year blood war collection', 'Bleach: Thousand - Year Blood War Collection'),
    ('yokohama stadium 27th september 1987', 'Live On Stage FM Broadcast - Yokohama Stadium 27th September 1987'),
    ('you & me', 'The Star That Voyages Far - Wuthering Waves v3.1 Cinematics - You & Me'),
    ('オリジナル・サウンドトラック', '86―エイティシックス― オリジナル・サウンドトラック'),
    ('僕の戦争', 'My War (Attack on Titan) - 僕の戦争'),
]


@pytest.mark.parametrize("tail,example", _REAL_TAILS)
def test_catalogue_real_tails_are_kept(tail, example):
    assert is_trailing_version_qualifier(tail) is False, (
        f"{tail!r} is part of the title (from {example!r}) but the rule dropped it"
    )
